<a href="https://colab.research.google.com/github/ShGamer16/C-123/blob/main/C_123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random
rewards = np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,-1,-1],
    [0,-1,-1,-1,-1,100],
    [-1,-1,-1,-1,0,100]
])

def set_initial_state():
  return np.random.randint(0,6)
  

In [10]:
set_initial_state()

1

In [11]:
def get_action(current_state,reward_matrix):
  available_action = []
  print('reward_matrix',reward_matrix)
  for action in enumerate(reward_matrix[current_state]):
    if action[1]!= -1:
      available_action.append(action[0])
  
  choose_action = random.choice(available_action)
  print('random choice of action from ',available_action,'is',choose_action)
  return choose_action

In [14]:
current_state = 4
action = get_action(current_state,rewards)
print(action)

reward_matrix [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
random choice of action from  [0, 5] is 0
0
